"""Blocked token

Revision ID: 180776bdcfd0
Revises: 39eb1692757e
Create Date: 2021-10-06 15:22:35.336914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180776bdcfd0'
down_revision = '39eb1692757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_token')
    # ### end Alembic commands ###
